/**
 * @cipherbox/crypto - Vault IPNS Derivation Tests
 *
 * Tests for deterministic vault IPNS keypair derivation and
 * domain separation from registry IPNS derivation.
 *
 * Test vectors generated from known private key to verify:
 * - Determinism: same key -> same output
 * - Domain separation: vault derivation != registry derivation
 * - Format: IPNS names start with k51
 * - Error handling: invalid key sizes rejected
 */

import { describe, it, expect } from 'vitest';
import * as secp256k1 from '@noble/secp256k1';
import { deriveVaultIpnsKeypair } from '../vault/derive-ipns';
import { CryptoError } from '../types';

// Known test private key (32 bytes)
const KNOWN_PRIVATE_KEY = new Uint8Array([
  0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
  0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e,
  0x1f, 0x20,
]);

// Pre-computed test vectors from KNOWN_PRIVATE_KEY.
// Generated by running deriveVaultIpnsKeypair and deriveRegistryIpnsKeypair
// with the known key. Registry value verifies domain separation.
const EXPECTED_VAULT_IPNS_NAME =
  'k51qzi5uqu5dm7fenqm7yzmi6tnm1098vdb0tjgm1full4pr0go19dk41asevo';
const EXPECTED_VAULT_PUBLIC_KEY =
  'f1aacff3867ca17fb8b800d20539288e012afe92303ef1e8001fe1a9a0a96854';
const EXPECTED_REGISTRY_IPNS_NAME =
  'k51qzi5uqu5dkdzj553fkqt6om6o0bui12dqboiea21zob1prcwx863usuzjxe';

function randomPrivateKey(): Uint8Array {
  return secp256k1.utils.randomPrivateKey();
}

describe('deriveVaultIpnsKeypair', () => {
  it('produces the same keypair and IPNS name for the same privateKey (determinism)', async () => {
    const privateKey = randomPrivateKey();
    const result1 = await deriveVaultIpnsKeypair(privateKey);
    const result2 = await deriveVaultIpnsKeypair(privateKey);

    expect(result1.privateKey).toEqual(result2.privateKey);
    expect(result1.publicKey).toEqual(result2.publicKey);
    expect(result1.ipnsName).toBe(result2.ipnsName);
  });

  it('produces different results for different private keys', async () => {
    const privateKey1 = randomPrivateKey();
    const privateKey2 = randomPrivateKey();
    const result1 = await deriveVaultIpnsKeypair(privateKey1);
    const result2 = await deriveVaultIpnsKeypair(privateKey2);

    expect(result1.ipnsName).not.toBe(result2.ipnsName);
    expect(result1.privateKey).not.toEqual(result2.privateKey);
    expect(result1.publicKey).not.toEqual(result2.publicKey);
  });

  it('matches expected test vectors for known private key', async () => {
    const result = await deriveVaultIpnsKeypair(KNOWN_PRIVATE_KEY);

    expect(result.ipnsName).toBe(EXPECTED_VAULT_IPNS_NAME);
    // Public key check ensures derivation algorithm hasn't changed
    expect(Buffer.from(result.publicKey).toString('hex')).toBe(EXPECTED_VAULT_PUBLIC_KEY);
  });

  it('produces a different IPNS name than registry derivation (domain separation)', async () => {
    // Domain separation: vault derivation uses a different HKDF context
    // than registry derivation, so the same private key produces different
    // IPNS names. We verify against pre-computed registry IPNS name.
    const result = await deriveVaultIpnsKeypair(KNOWN_PRIVATE_KEY);
    expect(result.ipnsName).not.toBe(EXPECTED_REGISTRY_IPNS_NAME);
  });

  it('throws CryptoError with INVALID_KEY_SIZE for 31-byte key', async () => {
    const shortKey = new Uint8Array(31);
    await expect(deriveVaultIpnsKeypair(shortKey)).rejects.toThrow(
      'Invalid private key size for vault derivation'
    );
    try {
      await deriveVaultIpnsKeypair(shortKey);
    } catch (error) {
      expect(error).toBeInstanceOf(CryptoError);
      expect((error as CryptoError).code).toBe('INVALID_KEY_SIZE');
    }
  });

  it('produces an IPNS name starting with k51', async () => {
    const privateKey = randomPrivateKey();
    const result = await deriveVaultIpnsKeypair(privateKey);
    expect(result.ipnsName).toMatch(/^k51/);
  });
});

describe('vault IPNS determinism (replaces initializeVault tests)', () => {
  it('deriveVaultIpnsKeypair is deterministic — same key always produces same result', async () => {
    // This replaces the initializeVault determinism test.
    // initializeVault delegates IPNS derivation to deriveVaultIpnsKeypair,
    // so testing the crypto primitive directly is sufficient.
    const privateKey = randomPrivateKey();
    const result1 = await deriveVaultIpnsKeypair(privateKey);
    const result2 = await deriveVaultIpnsKeypair(privateKey);

    expect(result1.publicKey).toEqual(result2.publicKey);
    expect(result1.privateKey).toEqual(result2.privateKey);
    expect(result1.ipnsName).toBe(result2.ipnsName);
  });
});
