/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { PublishIpnsDto, PublishIpnsResponseDto } from '../models';

import { customInstance } from '../custom-instance';

/**
 * Relay a pre-signed IPNS record to the IPFS network via delegated routing. The client signs the record locally; backend relays to delegated-ipfs.dev and tracks the folder for TEE republishing.
 * @summary Publish IPNS record
 */
export const ipnsControllerPublishRecord = (
  publishIpnsDto: PublishIpnsDto,
  signal?: AbortSignal
) => {
  return customInstance<PublishIpnsResponseDto>({
    url: `/ipns/publish`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: publishIpnsDto,
    signal,
  });
};

export const getIpnsControllerPublishRecordMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
    TError,
    { data: PublishIpnsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
  TError,
  { data: PublishIpnsDto },
  TContext
> => {
  const mutationKey = ['ipnsControllerPublishRecord'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
    { data: PublishIpnsDto }
  > = (props) => {
    const { data } = props ?? {};

    return ipnsControllerPublishRecord(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpnsControllerPublishRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>
>;
export type IpnsControllerPublishRecordMutationBody = PublishIpnsDto;
export type IpnsControllerPublishRecordMutationError = void;

/**
 * @summary Publish IPNS record
 */
export const useIpnsControllerPublishRecord = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
      TError,
      { data: PublishIpnsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
  TError,
  { data: PublishIpnsDto },
  TContext
> => {
  const mutationOptions = getIpnsControllerPublishRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
