/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BatchPublishIpnsDto,
  BatchPublishIpnsResponseDto,
  IpnsControllerResolveRecordParams,
  PublishIpnsDto,
  PublishIpnsResponseDto,
  ResolveIpnsResponseDto,
} from '../models';

import { customInstance } from '../custom-instance';

/**
 * Relay a pre-signed IPNS record to the IPFS network via delegated routing. The client signs the record locally; backend relays to delegated-ipfs.dev and tracks the folder for TEE republishing.
 * @summary Publish IPNS record
 */
export const ipnsControllerPublishRecord = (
  publishIpnsDto: PublishIpnsDto,
  signal?: AbortSignal
) => {
  return customInstance<PublishIpnsResponseDto>({
    url: `/ipns/publish`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: publishIpnsDto,
    signal,
  });
};

export const getIpnsControllerPublishRecordMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
    TError,
    { data: PublishIpnsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
  TError,
  { data: PublishIpnsDto },
  TContext
> => {
  const mutationKey = ['ipnsControllerPublishRecord'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
    { data: PublishIpnsDto }
  > = (props) => {
    const { data } = props ?? {};

    return ipnsControllerPublishRecord(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpnsControllerPublishRecordMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>
>;
export type IpnsControllerPublishRecordMutationBody = PublishIpnsDto;
export type IpnsControllerPublishRecordMutationError = void;

/**
 * @summary Publish IPNS record
 */
export const useIpnsControllerPublishRecord = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
      TError,
      { data: PublishIpnsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipnsControllerPublishRecord>>,
  TError,
  { data: PublishIpnsDto },
  TContext
> => {
  const mutationOptions = getIpnsControllerPublishRecordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Publish multiple IPNS records (folder and/or file) in a single API call. Supports up to 200 records per batch with concurrency-limited processing. Partial success is allowed: individual record failures do not fail the batch.
 * @summary Batch publish IPNS records
 */
export const ipnsControllerPublishBatch = (
  batchPublishIpnsDto: BatchPublishIpnsDto,
  signal?: AbortSignal
) => {
  return customInstance<BatchPublishIpnsResponseDto>({
    url: `/ipns/publish-batch`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: batchPublishIpnsDto,
    signal,
  });
};

export const getIpnsControllerPublishBatchMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipnsControllerPublishBatch>>,
    TError,
    { data: BatchPublishIpnsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipnsControllerPublishBatch>>,
  TError,
  { data: BatchPublishIpnsDto },
  TContext
> => {
  const mutationKey = ['ipnsControllerPublishBatch'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipnsControllerPublishBatch>>,
    { data: BatchPublishIpnsDto }
  > = (props) => {
    const { data } = props ?? {};

    return ipnsControllerPublishBatch(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpnsControllerPublishBatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipnsControllerPublishBatch>>
>;
export type IpnsControllerPublishBatchMutationBody = BatchPublishIpnsDto;
export type IpnsControllerPublishBatchMutationError = void;

/**
 * @summary Batch publish IPNS records
 */
export const useIpnsControllerPublishBatch = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipnsControllerPublishBatch>>,
      TError,
      { data: BatchPublishIpnsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipnsControllerPublishBatch>>,
  TError,
  { data: BatchPublishIpnsDto },
  TContext
> => {
  const mutationOptions = getIpnsControllerPublishBatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Resolve an IPNS name to its current CID via delegated routing. Returns the CID and sequence number of the current IPNS record.
 * @summary Resolve IPNS name
 */
export const ipnsControllerResolveRecord = (
  params: IpnsControllerResolveRecordParams,
  signal?: AbortSignal
) => {
  return customInstance<ResolveIpnsResponseDto>({
    url: `/ipns/resolve`,
    method: 'GET',
    params,
    signal,
  });
};

export const getIpnsControllerResolveRecordQueryKey = (
  params?: IpnsControllerResolveRecordParams
) => {
  return [`/ipns/resolve`, ...(params ? [params] : [])] as const;
};

export const getIpnsControllerResolveRecordQueryOptions = <
  TData = Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
  TError = void,
>(
  params: IpnsControllerResolveRecordParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIpnsControllerResolveRecordQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>> = ({
    signal,
  }) => ipnsControllerResolveRecord(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type IpnsControllerResolveRecordQueryResult = NonNullable<
  Awaited<ReturnType<typeof ipnsControllerResolveRecord>>
>;
export type IpnsControllerResolveRecordQueryError = void;

export function useIpnsControllerResolveRecord<
  TData = Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
  TError = void,
>(
  params: IpnsControllerResolveRecordParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
          TError,
          Awaited<ReturnType<typeof ipnsControllerResolveRecord>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIpnsControllerResolveRecord<
  TData = Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
  TError = void,
>(
  params: IpnsControllerResolveRecordParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
          TError,
          Awaited<ReturnType<typeof ipnsControllerResolveRecord>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIpnsControllerResolveRecord<
  TData = Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
  TError = void,
>(
  params: IpnsControllerResolveRecordParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Resolve IPNS name
 */

export function useIpnsControllerResolveRecord<
  TData = Awaited<ReturnType<typeof ipnsControllerResolveRecord>>,
  TError = void,
>(
  params: IpnsControllerResolveRecordParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof ipnsControllerResolveRecord>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getIpnsControllerResolveRecordQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
