/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AuthMethodResponseDto,
  LinkMethodDto,
  LoginDto,
  LoginResponseDto,
  LogoutResponseDto,
  TokenResponseDto,
  UnlinkMethodDto,
  UnlinkMethodResponseDto,
} from '../models';

import { customInstance } from '../custom-instance';

/**
 * @summary Authenticate user with Web3Auth ID token
 */
export const authControllerLogin = (loginDto: LoginDto, signal?: AbortSignal) => {
  return customInstance<LoginResponseDto>({
    url: `/auth/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: loginDto,
    signal,
  });
};

export const getAuthControllerLoginMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: LoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationKey = ['authControllerLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    { data: LoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = LoginDto;
export type AuthControllerLoginMutationError = void;

/**
 * @summary Authenticate user with Web3Auth ID token
 */
export const useAuthControllerLogin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogin>>,
      TError,
      { data: LoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: LoginDto },
  TContext
> => {
  const mutationOptions = getAuthControllerLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Refresh access token using HTTP-only refresh token cookie
 */
export const authControllerRefresh = (signal?: AbortSignal) => {
  return customInstance<TokenResponseDto>({ url: `/auth/refresh`, method: 'POST', signal });
};

export const getAuthControllerRefreshMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerRefresh'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    void
  > = () => {
    return authControllerRefresh();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefresh>>
>;

export type AuthControllerRefreshMutationError = void;

/**
 * @summary Refresh access token using HTTP-only refresh token cookie
 */
export const useAuthControllerRefresh = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefresh>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext> => {
  const mutationOptions = getAuthControllerRefreshMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Logout user and invalidate all refresh tokens
 */
export const authControllerLogout = (signal?: AbortSignal) => {
  return customInstance<LogoutResponseDto>({ url: `/auth/logout`, method: 'POST', signal });
};

export const getAuthControllerLogoutMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogout>>,
    void
  > = () => {
    return authControllerLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = void;

/**
 * @summary Logout user and invalidate all refresh tokens
 */
export const useAuthControllerLogout = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  const mutationOptions = getAuthControllerLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get all linked auth methods for the current user
 */
export const authControllerGetMethods = (signal?: AbortSignal) => {
  return customInstance<AuthMethodResponseDto[]>({ url: `/auth/methods`, method: 'GET', signal });
};

export const getAuthControllerGetMethodsQueryKey = () => {
  return [`/auth/methods`] as const;
};

export const getAuthControllerGetMethodsQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetMethods>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMethods>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAuthControllerGetMethodsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof authControllerGetMethods>>> = ({
    signal,
  }) => authControllerGetMethods(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetMethods>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetMethodsQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetMethods>>
>;
export type AuthControllerGetMethodsQueryError = void;

export function useAuthControllerGetMethods<
  TData = Awaited<ReturnType<typeof authControllerGetMethods>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMethods>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMethods>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMethods>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetMethods<
  TData = Awaited<ReturnType<typeof authControllerGetMethods>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMethods>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetMethods>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetMethods>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAuthControllerGetMethods<
  TData = Awaited<ReturnType<typeof authControllerGetMethods>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMethods>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get all linked auth methods for the current user
 */

export function useAuthControllerGetMethods<
  TData = Awaited<ReturnType<typeof authControllerGetMethods>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof authControllerGetMethods>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAuthControllerGetMethodsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Link a new auth method to the current user account
 */
export const authControllerLinkMethod = (linkMethodDto: LinkMethodDto, signal?: AbortSignal) => {
  return customInstance<AuthMethodResponseDto[]>({
    url: `/auth/link`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: linkMethodDto,
    signal,
  });
};

export const getAuthControllerLinkMethodMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLinkMethod>>,
    TError,
    { data: LinkMethodDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLinkMethod>>,
  TError,
  { data: LinkMethodDto },
  TContext
> => {
  const mutationKey = ['authControllerLinkMethod'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLinkMethod>>,
    { data: LinkMethodDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLinkMethod(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLinkMethodMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLinkMethod>>
>;
export type AuthControllerLinkMethodMutationBody = LinkMethodDto;
export type AuthControllerLinkMethodMutationError = void;

/**
 * @summary Link a new auth method to the current user account
 */
export const useAuthControllerLinkMethod = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLinkMethod>>,
      TError,
      { data: LinkMethodDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLinkMethod>>,
  TError,
  { data: LinkMethodDto },
  TContext
> => {
  const mutationOptions = getAuthControllerLinkMethodMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Unlink an auth method from the current user account
 */
export const authControllerUnlinkMethod = (
  unlinkMethodDto: UnlinkMethodDto,
  signal?: AbortSignal
) => {
  return customInstance<UnlinkMethodResponseDto>({
    url: `/auth/unlink`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: unlinkMethodDto,
    signal,
  });
};

export const getAuthControllerUnlinkMethodMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerUnlinkMethod>>,
    TError,
    { data: UnlinkMethodDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerUnlinkMethod>>,
  TError,
  { data: UnlinkMethodDto },
  TContext
> => {
  const mutationKey = ['authControllerUnlinkMethod'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerUnlinkMethod>>,
    { data: UnlinkMethodDto }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerUnlinkMethod(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerUnlinkMethodMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerUnlinkMethod>>
>;
export type AuthControllerUnlinkMethodMutationBody = UnlinkMethodDto;
export type AuthControllerUnlinkMethodMutationError = void;

/**
 * @summary Unlink an auth method from the current user account
 */
export const useAuthControllerUnlinkMethod = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerUnlinkMethod>>,
      TError,
      { data: UnlinkMethodDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerUnlinkMethod>>,
  TError,
  { data: UnlinkMethodDto },
  TContext
> => {
  const mutationOptions = getAuthControllerUnlinkMethodMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
