/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateInviteDto,
  InviteResponseDto,
  ShareInvitesControllerListInvitesParams,
} from '.././models';

import { customInstance } from '.././custom-instance';

/**
 * Create a new invite link with the item key wrapped by an ephemeral public key. Returns the invite token for URL construction. Default expiry: 7 days.
 * @summary Create an invite link
 */
export const shareInvitesControllerCreateInvite = (
  createInviteDto: CreateInviteDto,
  signal?: AbortSignal
) => {
  return customInstance<InviteResponseDto>({
    url: `/shares/invites`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createInviteDto,
    signal,
  });
};

export const getShareInvitesControllerCreateInviteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>,
    TError,
    { data: CreateInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>,
  TError,
  { data: CreateInviteDto },
  TContext
> => {
  const mutationKey = ['shareInvitesControllerCreateInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>,
    { data: CreateInviteDto }
  > = (props) => {
    const { data } = props ?? {};

    return shareInvitesControllerCreateInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShareInvitesControllerCreateInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>
>;
export type ShareInvitesControllerCreateInviteMutationBody = CreateInviteDto;
export type ShareInvitesControllerCreateInviteMutationError = void;

/**
 * @summary Create an invite link
 */
export const useShareInvitesControllerCreateInvite = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>,
      TError,
      { data: CreateInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof shareInvitesControllerCreateInvite>>,
  TError,
  { data: CreateInviteDto },
  TContext
> => {
  const mutationOptions = getShareInvitesControllerCreateInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all active (unclaimed, unexpired) invite links created by the authenticated user for the specified item. Expired invites are auto-cleaned.
 * @summary List active invites for an item
 */
export const shareInvitesControllerListInvites = (
  params: ShareInvitesControllerListInvitesParams,
  signal?: AbortSignal
) => {
  return customInstance<InviteResponseDto[]>({
    url: `/shares/invites`,
    method: 'GET',
    params,
    signal,
  });
};

export const getShareInvitesControllerListInvitesQueryKey = (
  params?: ShareInvitesControllerListInvitesParams
) => {
  return [`/shares/invites`, ...(params ? [params] : [])] as const;
};

export const getShareInvitesControllerListInvitesQueryOptions = <
  TData = Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
  TError = void,
>(
  params: ShareInvitesControllerListInvitesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShareInvitesControllerListInvitesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>> = ({
    signal,
  }) => shareInvitesControllerListInvites(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShareInvitesControllerListInvitesQueryResult = NonNullable<
  Awaited<ReturnType<typeof shareInvitesControllerListInvites>>
>;
export type ShareInvitesControllerListInvitesQueryError = void;

export function useShareInvitesControllerListInvites<
  TData = Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
  TError = void,
>(
  params: ShareInvitesControllerListInvitesParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
          TError,
          Awaited<ReturnType<typeof shareInvitesControllerListInvites>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShareInvitesControllerListInvites<
  TData = Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
  TError = void,
>(
  params: ShareInvitesControllerListInvitesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
          TError,
          Awaited<ReturnType<typeof shareInvitesControllerListInvites>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShareInvitesControllerListInvites<
  TData = Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
  TError = void,
>(
  params: ShareInvitesControllerListInvitesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary List active invites for an item
 */

export function useShareInvitesControllerListInvites<
  TData = Awaited<ReturnType<typeof shareInvitesControllerListInvites>>,
  TError = void,
>(
  params: ShareInvitesControllerListInvitesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shareInvitesControllerListInvites>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getShareInvitesControllerListInvitesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Revoke an active invite link. Only the original sharer can revoke. Already-claimed shares persist independently.
 * @summary Revoke an invite link
 */
export const shareInvitesControllerRevokeInvite = (inviteId: string) => {
  return customInstance<void>({ url: `/shares/invites/${inviteId}`, method: 'DELETE' });
};

export const getShareInvitesControllerRevokeInviteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>,
    TError,
    { inviteId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationKey = ['shareInvitesControllerRevokeInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>,
    { inviteId: string }
  > = (props) => {
    const { inviteId } = props ?? {};

    return shareInvitesControllerRevokeInvite(inviteId);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShareInvitesControllerRevokeInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>
>;

export type ShareInvitesControllerRevokeInviteMutationError = void;

/**
 * @summary Revoke an invite link
 */
export const useShareInvitesControllerRevokeInvite = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>,
      TError,
      { inviteId: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof shareInvitesControllerRevokeInvite>>,
  TError,
  { inviteId: string },
  TContext
> => {
  const mutationOptions = getShareInvitesControllerRevokeInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
