/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ClaimInviteDto,
  ClaimInviteResponseDto,
  InviteDataResponseDto,
  InviteStatusResponseDto,
} from '../models';

import { customInstance } from '../custom-instance';

/**
 * Check the status of an invite link. Returns only status -- no file name or sharer identity is revealed before authentication.
 * @summary Get invite status (public)
 */
export const invitesControllerGetInviteStatus = (token: string, signal?: AbortSignal) => {
  return customInstance<InviteStatusResponseDto>({
    url: `/invites/${token}`,
    method: 'GET',
    signal,
  });
};

export const getInvitesControllerGetInviteStatusQueryKey = (token?: string) => {
  return [`/invites/${token}`] as const;
};

export const getInvitesControllerGetInviteStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitesControllerGetInviteStatusQueryKey(token);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>> = ({
    signal,
  }) => invitesControllerGetInviteStatus(token, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitesControllerGetInviteStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>
>;
export type InvitesControllerGetInviteStatusQueryError = void;

export function useInvitesControllerGetInviteStatus<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
  TError = void,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
          TError,
          Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvitesControllerGetInviteStatus<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
          TError,
          Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvitesControllerGetInviteStatus<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get invite status (public)
 */

export function useInvitesControllerGetInviteStatus<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteStatus>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvitesControllerGetInviteStatusQueryOptions(token, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Fetch full invite data including encrypted key ciphertext. Requires authentication. Used by the client claim flow.
 * @summary Get invite data for claim flow (authenticated)
 */
export const invitesControllerGetInviteData = (token: string, signal?: AbortSignal) => {
  return customInstance<InviteDataResponseDto>({
    url: `/invites/${token}/data`,
    method: 'GET',
    signal,
  });
};

export const getInvitesControllerGetInviteDataQueryKey = (token?: string) => {
  return [`/invites/${token}/data`] as const;
};

export const getInvitesControllerGetInviteDataQueryOptions = <
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteData>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvitesControllerGetInviteDataQueryKey(token);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invitesControllerGetInviteData>>> = ({
    signal,
  }) => invitesControllerGetInviteData(token, signal);

  return { queryKey, queryFn, enabled: !!token, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvitesControllerGetInviteDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof invitesControllerGetInviteData>>
>;
export type InvitesControllerGetInviteDataQueryError = void;

export function useInvitesControllerGetInviteData<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
  TError = void,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteData>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
          TError,
          Awaited<ReturnType<typeof invitesControllerGetInviteData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvitesControllerGetInviteData<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteData>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
          TError,
          Awaited<ReturnType<typeof invitesControllerGetInviteData>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvitesControllerGetInviteData<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get invite data for claim flow (authenticated)
 */

export function useInvitesControllerGetInviteData<
  TData = Awaited<ReturnType<typeof invitesControllerGetInviteData>>,
  TError = void,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invitesControllerGetInviteData>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvitesControllerGetInviteDataQueryOptions(token, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Claim an invite by providing the item key re-wrapped for the recipient. Creates Share and ShareKey records. Single-claim enforced atomically.
 * @summary Claim an invite link
 */
export const invitesControllerClaimInvite = (
  token: string,
  claimInviteDto: ClaimInviteDto,
  signal?: AbortSignal
) => {
  return customInstance<ClaimInviteResponseDto>({
    url: `/invites/${token}/claim`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: claimInviteDto,
    signal,
  });
};

export const getInvitesControllerClaimInviteMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invitesControllerClaimInvite>>,
    TError,
    { token: string; data: ClaimInviteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invitesControllerClaimInvite>>,
  TError,
  { token: string; data: ClaimInviteDto },
  TContext
> => {
  const mutationKey = ['invitesControllerClaimInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invitesControllerClaimInvite>>,
    { token: string; data: ClaimInviteDto }
  > = (props) => {
    const { token, data } = props ?? {};

    return invitesControllerClaimInvite(token, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvitesControllerClaimInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof invitesControllerClaimInvite>>
>;
export type InvitesControllerClaimInviteMutationBody = ClaimInviteDto;
export type InvitesControllerClaimInviteMutationError = void;

/**
 * @summary Claim an invite link
 */
export const useInvitesControllerClaimInvite = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invitesControllerClaimInvite>>,
      TError,
      { token: string; data: ClaimInviteDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invitesControllerClaimInvite>>,
  TError,
  { token: string; data: ClaimInviteDto },
  TContext
> => {
  const mutationOptions = getInvitesControllerClaimInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
