/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface AddResponseDto {
  /** The IPFS CID of the pinned file */
  cid: string;
  /** The size of the pinned file in bytes */
  size: number;
}
