/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { ShareKeyEntryDto } from './shareKeyEntryDto';

export interface AddShareKeysDto {
  /** Array of re-wrapped keys to add to the share */
  keys: ShareKeyEntryDto[];
}
