/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of key: file or folder
 */
export type ChildKeyDtoKeyType = (typeof ChildKeyDtoKeyType)[keyof typeof ChildKeyDtoKeyType];

export const ChildKeyDtoKeyType = {
  file: 'file',
  folder: 'folder',
} as const;
