/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of shared item
 */
export type CreateShareDtoItemType =
  (typeof CreateShareDtoItemType)[keyof typeof CreateShareDtoItemType];

export const CreateShareDtoItemType = {
  folder: 'folder',
  file: 'file',
} as const;
