/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { CreateShareResponseDtoItemType } from './createShareResponseDtoItemType';

export interface CreateShareResponseDto {
  /** UUID of the created share */
  shareId: string;
  /** UUID of the recipient user */
  recipientId: string;
  itemType: CreateShareResponseDtoItemType;
  /** IPNS name of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  /** Hex-encoded ECIES-wrapped key for recipient */
  encryptedKey: string;
  /** When the share was created */
  createdAt: string;
}
