/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { DerivationInfoDtoMethod } from './derivationInfoDtoMethod';
import type { DerivationInfoDtoDerivationVersion } from './derivationInfoDtoDerivationVersion';

export interface DerivationInfoDto {
  /** Authentication method used to derive the private key. "web3auth" = social login (key managed by Web3Auth MPC), "external-wallet" = EIP-712 signature-derived key. */
  method: DerivationInfoDtoMethod;
  /**
   * Key derivation version for external wallet users. null for social logins, 1+ for external wallet derivation versions.
   * @nullable
   */
  derivationVersion: DerivationInfoDtoDerivationVersion;
}
