/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Authentication method used to derive the private key. "web3auth" = social login (key managed by Web3Auth MPC), "external-wallet" = EIP-712 signature-derived key.
 */
export type DerivationInfoDtoMethod =
  (typeof DerivationInfoDtoMethod)[keyof typeof DerivationInfoDtoMethod];

export const DerivationInfoDtoMethod = {
  web3auth: 'web3auth',
  'external-wallet': 'external-wallet',
} as const;
