/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Key derivation version for external wallet users. null for social logins, 1+ for external wallet derivation versions.
 * @nullable
 */
export type DerivationInfoDtoDerivationVersion = { [key: string]: unknown } | null;
