/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface IdentityTokenResponseDto {
  /** CipherBox-signed RS256 JWT for Web3Auth custom verifier (sub=userId) */
  idToken: string;
  /** CipherBox internal user UUID */
  userId: string;
  /** Whether this is a newly created user */
  isNewUser: boolean;
  /** Verified email address from the identity provider */
  email?: string;
}
