/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { InviteResponseDtoItemType } from './inviteResponseDtoItemType';
import type { InviteResponseDtoStatus } from './inviteResponseDtoStatus';

export interface InviteResponseDto {
  /** Invite token (URL-safe base64) */
  token: string;
  itemType: InviteResponseDtoItemType;
  /** IPNS name of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  status: InviteResponseDtoStatus;
  /** When the invite expires */
  expiresAt: string;
  /** When the invite was created */
  createdAt: string;
}
