/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Array of child keys wrapped with ephemeral public key, or null
 * @nullable
 */
export type InviteDataResponseDtoEncryptedChildKeys = { [key: string]: unknown } | null;
