/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of key: file or folder
 */
export type InviteChildKeyDtoKeyType =
  (typeof InviteChildKeyDtoKeyType)[keyof typeof InviteChildKeyDtoKeyType];

export const InviteChildKeyDtoKeyType = {
  file: 'file',
  folder: 'folder',
} as const;
