/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Current status of the invite
 */
export type InviteStatusResponseDtoStatus =
  (typeof InviteStatusResponseDtoStatus)[keyof typeof InviteStatusResponseDtoStatus];

export const InviteStatusResponseDtoStatus = {
  active: 'active',
  expired: 'expired',
  claimed: 'claimed',
  revoked: 'revoked',
} as const;
