/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Auth method type to link
 */
export type LinkMethodDtoLoginType =
  (typeof LinkMethodDtoLoginType)[keyof typeof LinkMethodDtoLoginType];

export const LinkMethodDtoLoginType = {
  google: 'google',
  email: 'email',
  wallet: 'wallet',
} as const;
