/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Login type
 */
export type LinkMethodDtoLoginType =
  (typeof LinkMethodDtoLoginType)[keyof typeof LinkMethodDtoLoginType];

export const LinkMethodDtoLoginType = {
  social: 'social',
  external_wallet: 'external_wallet',
} as const;
