/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { LinkMethodDtoLoginType } from './linkMethodDtoLoginType';

export interface LinkMethodDto {
  /** Web3Auth ID token from the new auth method */
  idToken: string;
  /** Login type */
  loginType: LinkMethodDtoLoginType;
}
