/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { LinkMethodDtoLoginType } from './linkMethodDtoLoginType';

export interface LinkMethodDto {
  /** CipherBox-issued JWT identity token for the new auth method */
  idToken: string;
  /** Auth method type to link */
  loginType: LinkMethodDtoLoginType;
  /** Wallet address (required when loginType is wallet) */
  walletAddress?: string;
  /** SIWE message (required when loginType is wallet) */
  siweMessage?: string;
  /** SIWE signature (required when loginType is wallet) */
  siweSignature?: string;
}
