/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of login used
 */
export type LoginDtoLoginType = (typeof LoginDtoLoginType)[keyof typeof LoginDtoLoginType];

export const LoginDtoLoginType = {
  social: 'social',
  external_wallet: 'external_wallet',
  corekit: 'corekit',
} as const;
