/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { LoginDtoLoginType } from './loginDtoLoginType';

export interface LoginDto {
  /** CipherBox-issued JWT identity token */
  idToken: string;
  /** secp256k1 public key exported from Core Kit after loginWithJWT */
  publicKey: string;
  /** Type of login used (always corekit) */
  loginType: LoginDtoLoginType;
}
