/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { LoginDtoLoginType } from './loginDtoLoginType';

export interface LoginDto {
  /** JWT ID token from Web3Auth */
  idToken: string;
  /** secp256k1 public key for social login, or signature-derived public key for external wallet (ADR-001) */
  publicKey: string;
  /** Type of login used */
  loginType: LoginDtoLoginType;
  /** Wallet address for external wallet users. Used for JWT verification. The publicKey field contains the derived key. */
  walletAddress?: string;
  /**
   * Key derivation version for external wallet users (ADR-001). Required for external_wallet loginType.
   * @minimum 1
   */
  derivationVersion?: number;
}
