/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { PendingRotationResponseDtoItemType } from './pendingRotationResponseDtoItemType';

export interface PendingRotationResponseDto {
  shareId: string;
  /** Recipient secp256k1 public key (0x04...) */
  recipientPublicKey: string;
  itemType: PendingRotationResponseDtoItemType;
  ipnsName: string;
  itemName: string;
  revokedAt: string;
}
