/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface PublishIpnsDto {
  /** IPNS name (k51... CIDv1 format) */
  ipnsName: string;
  /** Base64-encoded marshaled IPNS record */
  record: string;
  /** CID of the encrypted metadata this record points to */
  metadataCid: string;
  /** Hex-encoded ECIES-wrapped Ed25519 private key for TEE republishing (required on first publish) */
  encryptedIpnsPrivateKey?: string;
  /** TEE key epoch (required with encryptedIpnsPrivateKey) */
  keyEpoch?: number;
}
