/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface PublishIpnsResponseDto {
  /** Whether the publish operation succeeded */
  success: boolean;
  /** IPNS name that was published */
  ipnsName: string;
  /** Current sequence number (bigint as string) */
  sequenceNumber: string;
}
