/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { ReceivedShareResponseDtoItemType } from './receivedShareResponseDtoItemType';

export interface ReceivedShareResponseDto {
  shareId: string;
  /** Sharer secp256k1 public key (0x04...) */
  sharerPublicKey: string;
  itemType: ReceivedShareResponseDtoItemType;
  ipnsName: string;
  itemName: string;
  /** Hex-encoded ECIES-wrapped key for recipient */
  encryptedKey: string;
  createdAt: string;
}
