/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface ResolveIpnsResponseDto {
  /** Whether the resolution succeeded */
  success: boolean;
  /** CID that the IPNS name currently points to */
  cid: string;
  /** Current sequence number of the IPNS record (bigint as string) */
  sequenceNumber: string;
}
