/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface ResolveIpnsResponseDto {
  /** Whether the resolution succeeded */
  success: boolean;
  /** CID that the IPNS name currently points to */
  cid: string;
  /** Current sequence number of the IPNS record (bigint as string) */
  sequenceNumber: string;
  /** Base64-encoded Ed25519 signature (64 bytes) from the IPNS record. Only present when resolved from delegated routing (not DB cache). */
  signatureV2?: string;
  /** Base64-encoded CBOR data that was signed. Only present when resolved from delegated routing (not DB cache). */
  data?: string;
  /** Base64-encoded raw Ed25519 public key (32 bytes). Only present when resolved from delegated routing (not DB cache). */
  pubKey?: string;
}
