/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Approval action
 */
export type RespondApprovalDtoAction =
  (typeof RespondApprovalDtoAction)[keyof typeof RespondApprovalDtoAction];

export const RespondApprovalDtoAction = {
  approve: 'approve',
  deny: 'deny',
} as const;
