/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type SharesControllerGetReceivedSharesParams = {
  /**
   * Maximum number of items to return
   */
  limit?: number;
  /**
   * Number of items to skip
   */
  offset?: number;
};
