/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { ShareKeyResponseDtoKeyType } from './shareKeyResponseDtoKeyType';

export interface ShareKeyResponseDto {
  keyType: ShareKeyResponseDtoKeyType;
  /** UUID of the file or folder */
  itemId: string;
  /** Hex-encoded ECIES-wrapped key for recipient */
  encryptedKey: string;
}
