/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type ShareKeyResponseDtoKeyType =
  (typeof ShareKeyResponseDtoKeyType)[keyof typeof ShareKeyResponseDtoKeyType];

export const ShareKeyResponseDtoKeyType = {
  file: 'file',
  folder: 'folder',
} as const;
