/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Previous epoch TEE secp256k1 public key (hex-encoded, null if no rotation has occurred)
 * @nullable
 */
export type TeeKeysDtoPreviousPublicKey = { [key: string]: unknown } | null;
