/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Previous TEE key epoch number (null if no rotation has occurred)
 * @nullable
 */
export type TeeKeysDtoPreviousEpoch = { [key: string]: unknown } | null;
