/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface TestLoginResponseDto {
  /** JWT access token */
  accessToken: string;
  /** Refresh token */
  refreshToken: string;
  /** Whether this is a newly created user */
  isNewUser: boolean;
  /** Uncompressed secp256k1 public key (hex, 130 chars) */
  publicKeyHex: string;
  /** secp256k1 private key (hex, 64 chars) */
  privateKeyHex: string;
}
