/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface TestLoginDto {
  /** Email address for the test user */
  email: string;
  /** Secret that must match TEST_LOGIN_SECRET env var */
  secret: string;
}
