/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface TokenResponseDto {
  /** New JWT access token */
  accessToken: string;
  /** New refresh token (only present for desktop clients using X-Client-Type: desktop header) */
  refreshToken?: string;
  /** User email from their most recently used email auth method */
  email?: string;
}
