/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { VaultResponseDtoInitializedAt } from './vaultResponseDtoInitializedAt';

export interface VaultResponseDto {
  /** Vault UUID */
  id: string;
  /** User secp256k1 public key (uncompressed, 65 bytes, hex-encoded) */
  ownerPublicKey: string;
  /** ECIES-wrapped root folder AES-256 key (hex-encoded) */
  encryptedRootFolderKey: string;
  /** ECIES-wrapped Ed25519 IPNS private key (hex-encoded) */
  encryptedRootIpnsPrivateKey: string;
  /** Ed25519 IPNS public key (32 bytes, hex-encoded) */
  rootIpnsPublicKey: string;
  /** IPNS name for root folder */
  rootIpnsName: string;
  /** Vault creation timestamp */
  createdAt: string;
  /**
   * When vault was first used (first file uploaded), null if unused
   * @nullable
   */
  initializedAt: VaultResponseDtoInitializedAt;
}
