/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { DerivationInfoDto } from './derivationInfoDto';

/**
 * Hints about how the private key was derived, to assist recovery tools
 * @nullable
 */
export type VaultExportDtoDerivationInfo = DerivationInfoDto | null;
