/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Key derivation method used. Always "web3auth" for Core Kit users. Null if user record not found.
 * @nullable
 */
export type VaultExportDtoDerivationMethod = { [key: string]: unknown } | null;
