/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthMethodResponseDtoType } from './authMethodResponseDtoType';

export interface AuthMethodResponseDto {
  id: string;
  type: AuthMethodResponseDtoType;
  /** Email or wallet address */
  identifier: string;
  /** @nullable */
  lastUsedAt: string | null;
  createdAt: string;
}
