/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type AuthMethodResponseDtoType =
  (typeof AuthMethodResponseDtoType)[keyof typeof AuthMethodResponseDtoType];

export const AuthMethodResponseDtoType = {
  google: 'google',
  apple: 'apple',
  github: 'github',
  email: 'email',
  wallet: 'wallet',
} as const;
