/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { PublishIpnsResponseDto } from './publishIpnsResponseDto';

export interface BatchPublishIpnsResponseDto {
  /** Per-record publish results */
  results: PublishIpnsResponseDto[];
  /** Number of records that succeeded */
  totalSucceeded: number;
  /** Number of records that failed */
  totalFailed: number;
}
