/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { PublishIpnsEntryDto } from './publishIpnsEntryDto';

export interface BatchPublishIpnsDto {
  /** Array of IPNS records to publish (max 200) */
  records: PublishIpnsEntryDto[];
}
