/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

export interface BatchUnenrollIpnsResponseDto {
  /** Number of IPNS names successfully unenrolled */
  totalUnenrolled: number;
  /** Total IPNS names in the request */
  totalRequested: number;
}
