/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export interface BatchUnenrollIpnsDto {
  /** Array of IPNS names to unenroll from TEE republishing (max 200) */
  ipnsNames: string[];
}
