/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.40.0
 */

/**
 * Type of key: file, folder, or file-ipns
 */
export type ChildKeyDtoKeyType = (typeof ChildKeyDtoKeyType)[keyof typeof ChildKeyDtoKeyType];

export const ChildKeyDtoKeyType = {
  file: 'file',
  folder: 'folder',
  'file-ipns': 'file-ipns',
  'folder-ipns': 'folder-ipns',
} as const;
