/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */
import type { ChildKeyDtoKeyType } from './childKeyDtoKeyType';

export interface ChildKeyDto {
  /** Type of key: file, folder, or file-ipns */
  keyType: ChildKeyDtoKeyType;
  /** UUID of the file or subfolder */
  itemId: string;
  /** Hex-encoded ECIES ciphertext of the key wrapped for recipient */
  encryptedKey: string;
}
