/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */

/**
 * Type of key: file, folder, or file-ipns
 */
export type ClaimChildKeyDtoKeyType =
  (typeof ClaimChildKeyDtoKeyType)[keyof typeof ClaimChildKeyDtoKeyType];

export const ClaimChildKeyDtoKeyType = {
  file: 'file',
  folder: 'folder',
  'file-ipns': 'file-ipns',
} as const;
