/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */
import type { ClaimChildKeyDtoKeyType } from './claimChildKeyDtoKeyType';

export interface ClaimChildKeyDto {
  /** Type of key: file, folder, or file-ipns */
  keyType: ClaimChildKeyDtoKeyType;
  /** UUID of the file or subfolder */
  itemId: string;
  /** Hex-encoded ECIES ciphertext of the key re-wrapped for recipient */
  encryptedKey: string;
}
