/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimChildKeyDto } from './claimChildKeyDto';

export interface ClaimInviteDto {
  /** Hex-encoded item key re-wrapped for the recipient via ECIES */
  encryptedKey: string;
  /** Re-wrapped child keys for subfolders/files */
  childKeys?: ClaimChildKeyDto[];
}
