/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface ClaimInviteDto {
  /** Hex-encoded ECIES encrypted key for read access re-wrapped for the recipient (claimer re-wraps the root readKey from the ephemeral key to their own pubkey). Server never sees plaintext (zero-knowledge). */
  encryptedReadKey: string;
  /** Hex-encoded ECIES encrypted key for write access re-wrapped for the recipient. Omit for read-only claim. */
  encryptedWriteKey?: string;
  /** Hex-encoded ECIES ciphertext of the display name re-wrapped for the recipient. Optional: omit if recipient can derive the name from their filesystem. */
  itemNameEncrypted?: string;
}
