/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export interface ClaimInviteResponseDto {
  /** UUID of the created share */
  shareId: string;
}
