/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface ConnectionTestRequestDto {
  /** ECIES-encrypted provider config (hex-encoded) */
  encryptedConfig: string;
  /** TEE epoch for key selection */
  epoch: number;
}
