/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.42.0
 */
import type { ConnectionTestResponseDtoProtocol } from './connectionTestResponseDtoProtocol';

export interface ConnectionTestResponseDto {
  /** Whether the connection test succeeded */
  success: boolean;
  /** Detected protocol */
  protocol?: ConnectionTestResponseDtoProtocol;
  /** Provider version string */
  version?: string;
  /** Probe latency in milliseconds */
  latencyMs: number;
  /** Error message on failure */
  error?: string;
}
