/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

/**
 * Detected protocol
 */
export type ConnectionTestResponseDtoProtocol =
  (typeof ConnectionTestResponseDtoProtocol)[keyof typeof ConnectionTestResponseDtoProtocol];

export const ConnectionTestResponseDtoProtocol = {
  kubo: 'kubo',
  psa: 'psa',
} as const;
