/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */
import type { CreateShareDtoItemType } from './createShareDtoItemType';
import type { CreateShareDtoPermission } from './createShareDtoPermission';
import type { ChildKeyDto } from './childKeyDto';

export interface CreateShareDto {
  /** Recipient secp256k1 public key (uncompressed, 0x04... format) */
  recipientPublicKey: string;
  /** Type of shared item */
  itemType: CreateShareDtoItemType;
  /** IPNS name (k51...) of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  /** Hex-encoded ECIES ciphertext of the display name wrapped for recipient. Optional during rollout: legacy clients still send plaintext itemName. */
  itemNameEncrypted?: string;
  /** Hex-encoded root key wrapped for recipient via ECIES */
  encryptedKey: string;
  /** Permission level for the share */
  permission?: CreateShareDtoPermission;
  /** Hex-encoded ECIES ciphertext of IPNS private key for write shares */
  encryptedIpnsKey?: string;
  /** Re-wrapped descendant keys (subfolder/file keys) */
  childKeys?: ChildKeyDto[];
}
