/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

/**
 * Type of shared item
 */
export type CreateInviteDtoItemType =
  (typeof CreateInviteDtoItemType)[keyof typeof CreateInviteDtoItemType];

export const CreateInviteDtoItemType = {
  folder: 'folder',
  file: 'file',
} as const;
