/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.37.1
 */

/**
 * Permission level
 */
export type CreateShareResponseDtoPermission =
  (typeof CreateShareResponseDtoPermission)[keyof typeof CreateShareResponseDtoPermission];

export const CreateShareResponseDtoPermission = {
  read: 'read',
  write: 'write',
} as const;
