/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export interface CreateApprovalDto {
  /** Device ID (SHA-256 hash of device Ed25519 public key) */
  deviceId: string;
  /** Human-readable device name (e.g., "Chrome on macOS") */
  deviceName: string;
  /** Ephemeral secp256k1 public key in hex (uncompressed) for ECIES key exchange */
  ephemeralPublicKey: string;
}
