/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface CreateShareDto {
  /** Recipient secp256k1 public key (uncompressed, 0x04... format) */
  recipientPublicKey: string;
  /** Hex-encoded ECIES descriptor ref for read access (wrapped root readKey + metadata). Server never sees plaintext (zero-knowledge). */
  readDescriptorRef: string;
  /** Hex-encoded ECIES descriptor ref for write access. Presence signals a write grant (D-09). Omit for read-only shares. */
  writeDescriptorRef?: string;
  /** UUID of the root shared node (folder or file) */
  rootNodeId: string;
  /** IPNS name (k51...) of the root shared node */
  rootIpnsName: string;
  /** Generation of the root node at share time (numeric string) */
  rootGeneration?: string;
  /** Hex-encoded ECIES ciphertext of the display name wrapped for recipient. Optional: omit if recipient can derive the name from their filesystem. */
  itemNameEncrypted?: string;
}
