/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */

/**
 * Permission level for the share
 */
export type CreateShareDtoPermission =
  (typeof CreateShareDtoPermission)[keyof typeof CreateShareDtoPermission];

export const CreateShareDtoPermission = {
  read: 'read',
  write: 'write',
} as const;
