/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */
import type { CreateShareResponseDtoItemType } from './createShareResponseDtoItemType';
import type { CreateShareResponseDtoPermission } from './createShareResponseDtoPermission';

export interface CreateShareResponseDto {
  /** UUID of the created share */
  shareId: string;
  itemType: CreateShareResponseDtoItemType;
  /** IPNS name of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null for legacy rows
   * @nullable
   */
  itemNameEncrypted: string | null;
  /** Hex-encoded ECIES-wrapped key for recipient */
  encryptedKey: string;
  /** Permission level */
  permission: CreateShareResponseDtoPermission;
  /** When the share was created */
  createdAt: string;
}
