/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.0
 */

export interface DeleteAccountResponseDto {
  /** Whether the account was successfully deleted */
  success: boolean;
}
