/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.37.1
 */

export interface DesktopRefreshDto {
  /** Refresh token from previous login/refresh (required for desktop clients) */
  refreshToken?: string;
}
