/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type DeviceApprovalControllerGetPending200Item = {
  requestId?: string;
  deviceId?: string;
  deviceName?: string;
  ephemeralPublicKey?: string;
  createdAt?: string;
  expiresAt?: string;
};
