/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type DeviceApprovalControllerGetStatus200Status =
  (typeof DeviceApprovalControllerGetStatus200Status)[keyof typeof DeviceApprovalControllerGetStatus200Status];

export const DeviceApprovalControllerGetStatus200Status = {
  pending: 'pending',
  approved: 'approved',
  denied: 'denied',
  expired: 'expired',
} as const;
