/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.35.0
 */
import type { DeviceApprovalControllerGetStatus200Status } from './deviceApprovalControllerGetStatus200Status';

export type DeviceApprovalControllerGetStatus200 = {
  status?: DeviceApprovalControllerGetStatus200Status;
  /**
   * ECIES-encrypted factor key (hex)
   * @nullable
   */
  encryptedFactorKey?: string | null;
};
