/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { HealthControllerCheck503Info } from './healthControllerCheck503Info';
import type { HealthControllerCheck503Error } from './healthControllerCheck503Error';
import type { HealthControllerCheck503Details } from './healthControllerCheck503Details';

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};
