/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */
import type { HealthControllerCheck200DetailsDatabase } from './healthControllerCheck200DetailsDatabase';

export type HealthControllerCheck200Details = {
  database?: HealthControllerCheck200DetailsDatabase;
};
