/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.42.0
 */
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info';
import type { HealthControllerCheck200Error } from './healthControllerCheck200Error';
import type { HealthControllerCheck200Details } from './healthControllerCheck200Details';

export type HealthControllerCheck200 = {
  status: string;
  info?: HealthControllerCheck200Info;
  error?: HealthControllerCheck200Error;
  details: HealthControllerCheck200Details;
  version: string;
};
