/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { HealthControllerCheck200Info } from './healthControllerCheck200Info';

export type HealthControllerCheck200 = {
  status?: string;
  info?: HealthControllerCheck200Info;
};
