/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */
import type { HealthControllerCheck200InfoDatabase } from './healthControllerCheck200InfoDatabase';

export type HealthControllerCheck200Info = {
  database?: HealthControllerCheck200InfoDatabase;
};
