/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */
import type { IdentityControllerGetJwks200KeysItem } from './identityControllerGetJwks200KeysItem';

export type IdentityControllerGetJwks200 = {
  keys: IdentityControllerGetJwks200KeysItem[];
};
