/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.35.0
 */
import type { InviteStatusResponseDtoStatus } from './inviteStatusResponseDtoStatus';

export interface InviteStatusResponseDto {
  /** Invite status. Only "active" is returned; all other states result in 404 to prevent token-existence oracle attacks. */
  status: InviteStatusResponseDtoStatus;
}
