/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */

export type InviteDataResponseDtoItemType =
  (typeof InviteDataResponseDtoItemType)[keyof typeof InviteDataResponseDtoItemType];

export const InviteDataResponseDtoItemType = {
  folder: 'folder',
  file: 'file',
} as const;
