/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { InviteChildKeyDtoKeyType } from './inviteChildKeyDtoKeyType';

export interface InviteChildKeyDto {
  /** Type of key: file, folder, or file-ipns */
  keyType: InviteChildKeyDtoKeyType;
  /** UUID of the file or subfolder */
  itemId: string;
  /** Hex-encoded ECIES ciphertext of the key wrapped with ephemeral public key */
  encryptedKey: string;
}
