/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.37.1
 */

export type InviteResponseDtoItemType =
  (typeof InviteResponseDtoItemType)[keyof typeof InviteResponseDtoItemType];

export const InviteResponseDtoItemType = {
  folder: 'folder',
  file: 'file',
} as const;
