/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

/**
 * Invite status. Only "active" is returned; all other states result in 404 to prevent token-existence oracle attacks.
 */
export type InviteStatusResponseDtoStatus =
  (typeof InviteStatusResponseDtoStatus)[keyof typeof InviteStatusResponseDtoStatus];

export const InviteStatusResponseDtoStatus = {
  active: 'active',
} as const;
