/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.40.0
 */
import type { InviteResponseDtoItemType } from './inviteResponseDtoItemType';
import type { InviteResponseDtoStatus } from './inviteResponseDtoStatus';

export interface InviteResponseDto {
  /** Invite UUID (for management operations like revoke) */
  id: string;
  /** Invite token (URL-safe base64) */
  token: string;
  itemType: InviteResponseDtoItemType;
  /** IPNS name of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null for legacy invites
   * @nullable
   */
  itemNameEncrypted: string | null;
  status: InviteResponseDtoStatus;
  /** When the invite expires */
  expiresAt: string;
  /** When the invite was created */
  createdAt: string;
}
