/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */
import type { InviteDataResponseDtoStatus } from './inviteDataResponseDtoStatus';

export interface InviteDataResponseDto {
  /** Current status of the invite */
  status: InviteDataResponseDtoStatus;
  /** Hex-encoded root readKey wrapped with ephemeral public key */
  encryptedReadKey: string;
  /**
   * Hex-encoded ECIES encrypted key for write access wrapped with ephemeral public key. Null for read-only invites.
   * @nullable
   */
  encryptedWriteKey: string | null;
  /** UUID of the root shared node */
  rootNodeId: string;
  /** IPNS name of the root shared node */
  shareRootIpnsName: string;
  /** Generation of the root node at invite creation (numeric string) */
  rootGeneration: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null if not provided
   * @nullable
   */
  itemNameEncrypted: string | null;
}
