/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */
import type { InviteResponseDtoStatus } from './inviteResponseDtoStatus';

export interface InviteResponseDto {
  /** Invite UUID (for management operations like revoke) */
  id: string;
  /** Invite token (URL-safe base64) */
  token: string;
  /** IPNS name of the root shared node */
  shareRootIpnsName: string;
  /** UUID of the root shared node */
  rootNodeId: string;
  /** Generation of the root node at invite creation (numeric string) */
  rootGeneration: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null if not provided
   * @nullable
   */
  itemNameEncrypted: string | null;
  status: InviteResponseDtoStatus;
  /** When the invite expires */
  expiresAt: string;
  /** When the invite was created */
  createdAt: string;
}
