/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

/**
 * Current status of the invite
 */
export type InviteDataResponseDtoStatus =
  (typeof InviteDataResponseDtoStatus)[keyof typeof InviteDataResponseDtoStatus];

export const InviteDataResponseDtoStatus = {
  active: 'active',
  expired: 'expired',
  claimed: 'claimed',
  revoked: 'revoked',
} as const;
