/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */

export type InviteResponseDtoStatus =
  (typeof InviteResponseDtoStatus)[keyof typeof InviteResponseDtoStatus];

export const InviteResponseDtoStatus = {
  active: 'active',
  claimed: 'claimed',
  revoked: 'revoked',
} as const;
