/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.0
 */
import type { InviteDataResponseDtoStatus } from './inviteDataResponseDtoStatus';
import type { InviteChildKeyDto } from './inviteChildKeyDto';
import type { InviteDataResponseDtoItemType } from './inviteDataResponseDtoItemType';

export interface InviteDataResponseDto {
  /** Current status of the invite */
  status: InviteDataResponseDtoStatus;
  /** Hex-encoded item key wrapped with ephemeral public key */
  encryptedKey: string;
  /**
   * Array of child keys wrapped with ephemeral public key, or null
   * @nullable
   */
  encryptedChildKeys: InviteChildKeyDto[] | null;
  itemType: InviteDataResponseDtoItemType;
  /** IPNS name of the shared item */
  ipnsName: string;
  /** Display name of the shared item */
  itemName: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null for legacy invites
   * @nullable
   */
  itemNameEncrypted: string | null;
}
