/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */

/**
 * Type of key: file, folder, or file-ipns
 */
export type InviteChildKeyDtoKeyType =
  (typeof InviteChildKeyDtoKeyType)[keyof typeof InviteChildKeyDtoKeyType];

export const InviteChildKeyDtoKeyType = {
  file: 'file',
  folder: 'folder',
  'file-ipns': 'file-ipns',
} as const;
