/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */

export type IpfsControllerUploadBody = {
  /** Encrypted file blob (max 100MB) */
  file: Blob;
};
