/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.0
 */

/**
 * Type of login used (always corekit)
 */
export type LoginDtoLoginType = (typeof LoginDtoLoginType)[keyof typeof LoginDtoLoginType];

export const LoginDtoLoginType = {
  corekit: 'corekit',
} as const;
