/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface LoginResponseDto {
  /** JWT access token for API requests */
  accessToken: string;
  /** Whether this is a new user registration */
  isNewUser: boolean;
  /** Refresh token (only present for desktop clients using X-Client-Type: desktop header) */
  refreshToken?: string;
}
