/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export interface LookupUserResponseDto {
  /** Whether a registered user was found for the given public key */
  exists: boolean;
}
