/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { MigrationStatusDtoCompletedAt } from './migrationStatusDtoCompletedAt';

export interface MigrationStatusDto {
  id: string;
  status: string;
  totalCids: number;
  migratedCids: number;
  failedCids: number;
  createdAt: string;
  /** @nullable */
  completedAt: MigrationStatusDtoCompletedAt;
}
