/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.37.1
 */
import type { ReceivedShareResponseDto } from './receivedShareResponseDto';

export interface PaginatedReceivedSharesDto {
  shares: ReceivedShareResponseDto[];
  /**
   * Total number of matching shares
   * @minimum 0
   */
  total: number;
}
