/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */
import type { SentShareResponseDto } from './sentShareResponseDto';

export interface PaginatedSentSharesDto {
  shares: SentShareResponseDto[];
  /**
   * Total number of matching shares
   * @minimum 0
   */
  total: number;
}
