/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Record type: 'folder' for folder metadata, 'file' for per-file metadata
 */
export type PublishIpnsEntryDtoRecordType =
  (typeof PublishIpnsEntryDtoRecordType)[keyof typeof PublishIpnsEntryDtoRecordType];

export const PublishIpnsEntryDtoRecordType = {
  folder: 'folder',
  file: 'file',
} as const;
