/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.42.0
 */
import type { PublishIpnsEntryDtoRecordType } from './publishIpnsEntryDtoRecordType';

export interface PublishIpnsEntryDto {
  /** IPNS name (k51... CIDv1 format) */
  ipnsName: string;
  /** Base64-encoded marshaled IPNS record */
  record: string;
  /** Base64-encoded raw 32-byte Ed25519 public key for this IPNS name */
  publicKey?: string;
  /** CID of the encrypted metadata this record points to */
  metadataCid: string;
  /** Hex-encoded ECIES-wrapped Ed25519 private key for TEE republishing */
  encryptedIpnsPrivateKey?: string;
  /** TEE key epoch (required with encryptedIpnsPrivateKey) */
  keyEpoch?: number;
  /** Record type: 'folder' for folder metadata, 'file' for per-file metadata */
  recordType?: PublishIpnsEntryDtoRecordType;
  /** Expected sequence number for conflict detection. When present, the API validates against the stored value and rejects with 409 if mismatched. Omit for backward-compatible unconditional publish. */
  expectedSequenceNumber?: string;
}
