/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.37.1
 */

export interface QuotaResponseDto {
  /** Current storage usage in bytes */
  usedBytes: number;
  /** Maximum storage limit in bytes (500 MiB) */
  limitBytes: number;
  /** Remaining storage in bytes */
  remainingBytes: number;
  /** Whether quota is advisory-only (BYO users manage their own storage) */
  advisory: boolean;
}
