/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface ReceivedShareResponseDto {
  shareId: string;
  /** Sharer secp256k1 public key (0x04...) */
  sharerPublicKey: string;
  /** Hex-encoded ECIES encrypted key for read access */
  encryptedReadKey: string;
  /**
   * Hex-encoded ECIES encrypted key for write access, or null for read-only shares
   * @nullable
   */
  encryptedWriteKey: string | null;
  /** UUID of the root shared node */
  rootNodeId: string;
  /** IPNS name (k51...) of the root shared node */
  shareRootIpnsName: string;
  /** Generation of the root node at share creation (numeric string) */
  rootGeneration: string;
  /**
   * Hex-encoded ECIES ciphertext of the display name, or null if not provided
   * @nullable
   */
  itemNameEncrypted: string | null;
  createdAt: string;
}
