/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */

/**
 * Permission level
 */
export type ReceivedShareResponseDtoPermission =
  (typeof ReceivedShareResponseDtoPermission)[keyof typeof ReceivedShareResponseDtoPermission];

export const ReceivedShareResponseDtoPermission = {
  read: 'read',
  write: 'write',
} as const;
