/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.35.0
 */
import type { ReceivedShareResponseDtoItemType } from './receivedShareResponseDtoItemType';
import type { ReceivedShareResponseDtoPermission } from './receivedShareResponseDtoPermission';

export interface ReceivedShareResponseDto {
  shareId: string;
  /** Sharer secp256k1 public key (0x04...) */
  sharerPublicKey: string;
  itemType: ReceivedShareResponseDtoItemType;
  ipnsName: string;
  itemName: string;
  /** Hex-encoded ECIES-wrapped key for recipient */
  encryptedKey: string;
  /** Permission level */
  permission: ReceivedShareResponseDtoPermission;
  /**
   * Hex-encoded ECIES-wrapped IPNS private key for write shares
   * @nullable
   */
  encryptedIpnsKey: string | null;
  createdAt: string;
}
