/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */

export interface RegisterCidDto {
  /** IPFS CID pinned to external provider (CIDv0 or CIDv1) */
  cid: string;
  /** Size of the pinned content in bytes */
  sizeBytes: number;
}
