/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type RepublishHealthControllerGetHealth200 = {
  /** Active entries awaiting next republish cycle */
  pending?: number;
  /** Entries currently in retry with exponential backoff */
  failed?: number;
  /** Entries that exceeded max retries and need TEE recovery */
  stale?: number;
  /**
   * Timestamp of most recent successful republish
   * @nullable
   */
  lastRunAt?: string | null;
  /**
   * Current TEE key epoch number
   * @nullable
   */
  currentEpoch?: number | null;
  /** Whether the TEE worker is reachable and healthy */
  teeHealthy?: boolean;
};
