/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { RespondApprovalDtoAction } from './respondApprovalDtoAction';

export interface RespondApprovalDto {
  /** Approval action */
  action: RespondApprovalDtoAction;
  /** ECIES-encrypted factor key in hex (required when action is approve) */
  encryptedFactorKey?: string;
  /** Device ID of the responding (approving/denying) device */
  respondedByDeviceId: string;
}
