/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.0
 */

export interface RevokeForItemsDto {
  /** IPNS names (k51...) of every node in the deleted subtree. Shares/invites the caller created for any of these are hard-revoked. Unshared names are ignored. */
  ipnsNames: string[];
}
