/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.0
 */

export interface RevokeForItemsResponseDto {
  /** Number of Share rows hard-deleted (their ShareKeys cascade-deleted) */
  revokedShares: number;
  /** Number of active ShareInvite rows marked 'revoked' */
  revokedInvites: number;
}
