/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.41.0
 */

/**
 * Permission level
 */
export type SentShareResponseDtoPermission =
  (typeof SentShareResponseDtoPermission)[keyof typeof SentShareResponseDtoPermission];

export const SentShareResponseDtoPermission = {
  read: 'read',
  write: 'write',
} as const;
