/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { SentShareResponseDtoItemType } from './sentShareResponseDtoItemType';

export interface SentShareResponseDto {
  shareId: string;
  /** Recipient secp256k1 public key (0x04...) */
  recipientPublicKey: string;
  itemType: SentShareResponseDtoItemType;
  ipnsName: string;
  itemName: string;
  createdAt: string;
}
