/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export type SentShareResponseDtoItemType =
  (typeof SentShareResponseDtoItemType)[keyof typeof SentShareResponseDtoItemType];

export const SentShareResponseDtoItemType = {
  folder: 'folder',
  file: 'file',
} as const;
