/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export type ShareInvitesControllerListInvitesParams = {
  /**
   * IPNS name of the item to list invites for
   */
  ipnsName: string;
};
