/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.38.0
 */
import type { ShareKeyEntryDtoKeyType } from './shareKeyEntryDtoKeyType';

export interface ShareKeyEntryDto {
  /** Type of key: file, folder, file-ipns, or folder-ipns */
  keyType: ShareKeyEntryDtoKeyType;
  /** UUID of the file or subfolder */
  itemId: string;
  /** Hex-encoded ECIES ciphertext of the key wrapped for recipient */
  encryptedKey: string;
}
