/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export type ShareInvitesControllerListInvitesParams = {
  /**
   * IPNS name of the root shared node
   */
  shareRootIpnsName: string;
};
