/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Type of key: file, folder, or file-ipns
 */
export type ShareKeyEntryDtoKeyType =
  (typeof ShareKeyEntryDtoKeyType)[keyof typeof ShareKeyEntryDtoKeyType];

export const ShareKeyEntryDtoKeyType = {
  file: 'file',
  folder: 'folder',
  'file-ipns': 'file-ipns',
} as const;
