/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface StartMigrationDto {
  /** Source provider config encrypted with TEE public key (ECIES) */
  sourceConfigEncrypted: string;
  /** Destination provider config encrypted with TEE public key (ECIES) */
  destConfigEncrypted: string;
}
