/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.36.1
 */

export interface TeeKeysDto {
  /** Current TEE key epoch number */
  currentEpoch: number;
  /** Current epoch TEE secp256k1 public key (uncompressed, 65 bytes, hex-encoded) */
  currentPublicKey: string;
  /**
   * Previous TEE key epoch number (null if no rotation has occurred)
   * @nullable
   */
  previousEpoch: number | null;
  /**
   * Previous epoch TEE secp256k1 public key (hex-encoded, null if no rotation has occurred)
   * @nullable
   */
  previousPublicKey: string | null;
}
