/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface TombstoneIpnsDto {
  /** IPNS name to tombstone (k51... CIDv1 format) */
  ipnsName: string;
}
