/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */

/**
 * Permission level for the share
 */
export type UpdatePermissionDtoPermission =
  (typeof UpdatePermissionDtoPermission)[keyof typeof UpdatePermissionDtoPermission];

export const UpdatePermissionDtoPermission = {
  read: 'read',
  write: 'write',
} as const;
