/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.39.0
 */
import type { UpdatePermissionDtoPermission } from './updatePermissionDtoPermission';

export interface UpdatePermissionDto {
  /** Permission level for the share */
  permission: UpdatePermissionDtoPermission;
  /** Hex-encoded ECIES ciphertext of IPNS private key. Required when upgrading to write, omitted when downgrading to read. */
  encryptedIpnsKey?: string;
}
