/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface UpdateItemNameDto {
  /** Hex-encoded ECIES ciphertext of the display name wrapped for the recipient. Used to lazily backfill itemNameEncrypted on legacy shares created before at-rest encryption (decision A2). */
  itemNameEncrypted: string;
}
