/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface UpdateGrantDto {
  /** Hex-encoded ECIES encrypted key for read access, re-wrapped for the recipient after an owner rotation. The server stores the client-supplied ciphertext as-is. */
  encryptedReadKey: string;
  /** Generation of the root node the rotated key is rooted at (numeric string) */
  rootGeneration: string;
  /** Hex-encoded ECIES encrypted key for write access, set to upgrade a read-only share to write (read->write, D-09). Omit to leave any existing encryptedWriteKey unchanged (e.g. a read-key-rotation-only call). Mutually exclusive with clearEncryptedWriteKey. */
  encryptedWriteKey?: string;
  /** When true, clears any existing encryptedWriteKey (write->read downgrade). Omit/false to leave encryptedWriteKey unchanged. Mutually exclusive with encryptedWriteKey. */
  clearEncryptedWriteKey?: boolean;
}
