/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.44.1
 */

export interface UpdateGrantDto {
  /** Hex-encoded ECIES descriptor ref for read access, re-wrapped for the recipient after an owner rotation. The server stores the client-supplied ciphertext as-is. */
  readDescriptorRef: string;
  /** Generation of the root node the rotated descriptor is rooted at (numeric string) */
  rootGeneration: string;
}
