/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import type { TeeKeysDto } from './teeKeysDto';

/**
 * TEE public keys for IPNS key encryption (null if TEE not initialized)
 * @nullable
 */
export type VaultResponseDtoTeeKeys = TeeKeysDto | null;
