/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ECIES-wrapped Ed25519 IPNS private key (hex-encoded). Null for migrated v2 blob vaults.
 * @nullable
 */
export type VaultExportDtoEncryptedRootIpnsPrivateKey = { [key: string]: unknown } | null;
