/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * ECIES-wrapped root folder AES-256 key (hex-encoded). Null for migrated v2 blob vaults (rootFolderKey lives in IPFS).
 * @nullable
 */
export type VaultResponseDtoEncryptedRootFolderKey = { [key: string]: unknown } | null;
