/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

export interface VaultExportDto {
  /** Export format identifier */
  format: string;
  /** Export format version */
  version: string;
  /** ISO 8601 timestamp of when the export was created */
  exportedAt: string;
  /** IPNS name for the root folder (libp2p-key multihash) */
  rootIpnsName: string;
  /** ECIES-wrapped root folder AES-256 key (hex-encoded) */
  encryptedRootFolderKey: string;
  /** ECIES-wrapped Ed25519 IPNS private key (hex-encoded) */
  encryptedRootIpnsPrivateKey: string;
  /**
   * Key derivation method used. Always "web3auth" for Core Kit users. Null if user record not found.
   * @nullable
   */
  derivationMethod?: string | null;
}
