/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */

/**
 * Intent: "login" (default) creates/finds a user, "link" only verifies ownership
 */
export type VerifyOtpDtoIntent = (typeof VerifyOtpDtoIntent)[keyof typeof VerifyOtpDtoIntent];

export const VerifyOtpDtoIntent = {
  login: 'login',
  link: 'link',
} as const;
