/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  IpfsControllerUploadBody,
  UnpinDto,
  UnpinResponseDto,
  UploadResponseDto,
} from '../models';

import { customInstance } from '../custom-instance';

/**
 * Pins encrypted file to IPFS, checks storage quota, and records the pin for quota tracking. All in one atomic request.
 * @summary Upload encrypted file to IPFS with quota tracking
 */
export const ipfsControllerUpload = (
  ipfsControllerUploadBody: IpfsControllerUploadBody,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`file`, ipfsControllerUploadBody.file);

  return customInstance<UploadResponseDto>({
    url: `/ipfs/upload`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  });
};

export const getIpfsControllerUploadMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipfsControllerUpload>>,
    TError,
    { data: IpfsControllerUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipfsControllerUpload>>,
  TError,
  { data: IpfsControllerUploadBody },
  TContext
> => {
  const mutationKey = ['ipfsControllerUpload'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipfsControllerUpload>>,
    { data: IpfsControllerUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return ipfsControllerUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpfsControllerUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipfsControllerUpload>>
>;
export type IpfsControllerUploadMutationBody = IpfsControllerUploadBody;
export type IpfsControllerUploadMutationError = void;

/**
 * @summary Upload encrypted file to IPFS with quota tracking
 */
export const useIpfsControllerUpload = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipfsControllerUpload>>,
      TError,
      { data: IpfsControllerUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipfsControllerUpload>>,
  TError,
  { data: IpfsControllerUploadBody },
  TContext
> => {
  const mutationOptions = getIpfsControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Remove a pinned file from IPFS using its CID.
 * @summary Unpin file from IPFS
 */
export const ipfsControllerUnpin = (unpinDto: UnpinDto, signal?: AbortSignal) => {
  return customInstance<UnpinResponseDto>({
    url: `/ipfs/unpin`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: unpinDto,
    signal,
  });
};

export const getIpfsControllerUnpinMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipfsControllerUnpin>>,
    TError,
    { data: UnpinDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>,
  TError,
  { data: UnpinDto },
  TContext
> => {
  const mutationKey = ['ipfsControllerUnpin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipfsControllerUnpin>>,
    { data: UnpinDto }
  > = (props) => {
    const { data } = props ?? {};

    return ipfsControllerUnpin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpfsControllerUnpinMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>
>;
export type IpfsControllerUnpinMutationBody = UnpinDto;
export type IpfsControllerUnpinMutationError = void;

/**
 * @summary Unpin file from IPFS
 */
export const useIpfsControllerUnpin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipfsControllerUnpin>>,
      TError,
      { data: UnpinDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>,
  TError,
  { data: UnpinDto },
  TContext
> => {
  const mutationOptions = getIpfsControllerUnpinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Download an encrypted file from IPFS via the configured gateway.
 * @summary Get file from IPFS
 */
export const ipfsControllerGet = (cid: string, signal?: AbortSignal) => {
  return customInstance<Blob>({ url: `/ipfs/${cid}`, method: 'GET', responseType: 'blob', signal });
};

export const getIpfsControllerGetQueryKey = (cid?: string) => {
  return [`/ipfs/${cid}`] as const;
};

export const getIpfsControllerGetQueryOptions = <
  TData = Awaited<ReturnType<typeof ipfsControllerGet>>,
  TError = void,
>(
  cid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ipfsControllerGet>>, TError, TData>>;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIpfsControllerGetQueryKey(cid);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof ipfsControllerGet>>> = ({ signal }) =>
    ipfsControllerGet(cid, signal);

  return { queryKey, queryFn, enabled: !!cid, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof ipfsControllerGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type IpfsControllerGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof ipfsControllerGet>>
>;
export type IpfsControllerGetQueryError = void;

export function useIpfsControllerGet<
  TData = Awaited<ReturnType<typeof ipfsControllerGet>>,
  TError = void,
>(
  cid: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof ipfsControllerGet>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ipfsControllerGet>>,
          TError,
          Awaited<ReturnType<typeof ipfsControllerGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIpfsControllerGet<
  TData = Awaited<ReturnType<typeof ipfsControllerGet>>,
  TError = void,
>(
  cid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ipfsControllerGet>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ipfsControllerGet>>,
          TError,
          Awaited<ReturnType<typeof ipfsControllerGet>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIpfsControllerGet<
  TData = Awaited<ReturnType<typeof ipfsControllerGet>>,
  TError = void,
>(
  cid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ipfsControllerGet>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get file from IPFS
 */

export function useIpfsControllerGet<
  TData = Awaited<ReturnType<typeof ipfsControllerGet>>,
  TError = void,
>(
  cid: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof ipfsControllerGet>>, TError, TData>>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getIpfsControllerGetQueryOptions(cid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
