/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { AddResponseDto, IpfsControllerAddBody, UnpinDto, UnpinResponseDto } from '../models';

import { customInstance } from '../custom-instance';

/**
 * Upload an encrypted file blob to IPFS via Pinata. Returns the CID and size.
 * @summary Pin encrypted file to IPFS
 */
export const ipfsControllerAdd = (
  ipfsControllerAddBody: IpfsControllerAddBody,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  formData.append(`file`, ipfsControllerAddBody.file);

  return customInstance<AddResponseDto>({
    url: `/ipfs/add`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  });
};

export const getIpfsControllerAddMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipfsControllerAdd>>,
    TError,
    { data: IpfsControllerAddBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipfsControllerAdd>>,
  TError,
  { data: IpfsControllerAddBody },
  TContext
> => {
  const mutationKey = ['ipfsControllerAdd'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipfsControllerAdd>>,
    { data: IpfsControllerAddBody }
  > = (props) => {
    const { data } = props ?? {};

    return ipfsControllerAdd(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpfsControllerAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipfsControllerAdd>>
>;
export type IpfsControllerAddMutationBody = IpfsControllerAddBody;
export type IpfsControllerAddMutationError = void;

/**
 * @summary Pin encrypted file to IPFS
 */
export const useIpfsControllerAdd = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipfsControllerAdd>>,
      TError,
      { data: IpfsControllerAddBody },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipfsControllerAdd>>,
  TError,
  { data: IpfsControllerAddBody },
  TContext
> => {
  const mutationOptions = getIpfsControllerAddMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Remove a pinned file from IPFS via Pinata using its CID.
 * @summary Unpin file from IPFS
 */
export const ipfsControllerUnpin = (unpinDto: UnpinDto, signal?: AbortSignal) => {
  return customInstance<UnpinResponseDto>({
    url: `/ipfs/unpin`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: unpinDto,
    signal,
  });
};

export const getIpfsControllerUnpinMutationOptions = <TError = void, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof ipfsControllerUnpin>>,
    TError,
    { data: UnpinDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>,
  TError,
  { data: UnpinDto },
  TContext
> => {
  const mutationKey = ['ipfsControllerUnpin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof ipfsControllerUnpin>>,
    { data: UnpinDto }
  > = (props) => {
    const { data } = props ?? {};

    return ipfsControllerUnpin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IpfsControllerUnpinMutationResult = NonNullable<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>
>;
export type IpfsControllerUnpinMutationBody = UnpinDto;
export type IpfsControllerUnpinMutationError = void;

/**
 * @summary Unpin file from IPFS
 */
export const useIpfsControllerUnpin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof ipfsControllerUnpin>>,
      TError,
      { data: UnpinDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof ipfsControllerUnpin>>,
  TError,
  { data: UnpinDto },
  TContext
> => {
  const mutationOptions = getIpfsControllerUnpinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
