/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GoogleLoginDto,
  IdentityControllerGetJwks200,
  IdentityTokenResponseDto,
  SendOtpDto,
  SendOtpResponseDto,
  VerifyOtpDto,
} from '../models';

import { customInstance } from '../custom-instance';

/**
 * @summary JWKS endpoint for CipherBox identity provider
 */
export const identityControllerGetJwks = (signal?: AbortSignal) => {
  return customInstance<IdentityControllerGetJwks200>({
    url: `/auth/.well-known/jwks.json`,
    method: 'GET',
    signal,
  });
};

export const getIdentityControllerGetJwksQueryKey = () => {
  return [`/auth/.well-known/jwks.json`] as const;
};

export const getIdentityControllerGetJwksQueryOptions = <
  TData = Awaited<ReturnType<typeof identityControllerGetJwks>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof identityControllerGetJwks>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getIdentityControllerGetJwksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof identityControllerGetJwks>>> = ({
    signal,
  }) => identityControllerGetJwks(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof identityControllerGetJwks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type IdentityControllerGetJwksQueryResult = NonNullable<
  Awaited<ReturnType<typeof identityControllerGetJwks>>
>;
export type IdentityControllerGetJwksQueryError = unknown;

export function useIdentityControllerGetJwks<
  TData = Awaited<ReturnType<typeof identityControllerGetJwks>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof identityControllerGetJwks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof identityControllerGetJwks>>,
          TError,
          Awaited<ReturnType<typeof identityControllerGetJwks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIdentityControllerGetJwks<
  TData = Awaited<ReturnType<typeof identityControllerGetJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof identityControllerGetJwks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof identityControllerGetJwks>>,
          TError,
          Awaited<ReturnType<typeof identityControllerGetJwks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useIdentityControllerGetJwks<
  TData = Awaited<ReturnType<typeof identityControllerGetJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof identityControllerGetJwks>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary JWKS endpoint for CipherBox identity provider
 */

export function useIdentityControllerGetJwks<
  TData = Awaited<ReturnType<typeof identityControllerGetJwks>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof identityControllerGetJwks>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getIdentityControllerGetJwksQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Login with Google OAuth token, returns CipherBox identity JWT
 */
export const identityControllerGoogleLogin = (
  googleLoginDto: GoogleLoginDto,
  signal?: AbortSignal
) => {
  return customInstance<IdentityTokenResponseDto>({
    url: `/auth/identity/google`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: googleLoginDto,
    signal,
  });
};

export const getIdentityControllerGoogleLoginMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityControllerGoogleLogin>>,
    TError,
    { data: GoogleLoginDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityControllerGoogleLogin>>,
  TError,
  { data: GoogleLoginDto },
  TContext
> => {
  const mutationKey = ['identityControllerGoogleLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityControllerGoogleLogin>>,
    { data: GoogleLoginDto }
  > = (props) => {
    const { data } = props ?? {};

    return identityControllerGoogleLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityControllerGoogleLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityControllerGoogleLogin>>
>;
export type IdentityControllerGoogleLoginMutationBody = GoogleLoginDto;
export type IdentityControllerGoogleLoginMutationError = void;

/**
 * @summary Login with Google OAuth token, returns CipherBox identity JWT
 */
export const useIdentityControllerGoogleLogin = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityControllerGoogleLogin>>,
      TError,
      { data: GoogleLoginDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityControllerGoogleLogin>>,
  TError,
  { data: GoogleLoginDto },
  TContext
> => {
  const mutationOptions = getIdentityControllerGoogleLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Send OTP to email address
 */
export const identityControllerSendOtp = (sendOtpDto: SendOtpDto, signal?: AbortSignal) => {
  return customInstance<SendOtpResponseDto>({
    url: `/auth/identity/email/send-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendOtpDto,
    signal,
  });
};

export const getIdentityControllerSendOtpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityControllerSendOtp>>,
    TError,
    { data: SendOtpDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityControllerSendOtp>>,
  TError,
  { data: SendOtpDto },
  TContext
> => {
  const mutationKey = ['identityControllerSendOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityControllerSendOtp>>,
    { data: SendOtpDto }
  > = (props) => {
    const { data } = props ?? {};

    return identityControllerSendOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityControllerSendOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityControllerSendOtp>>
>;
export type IdentityControllerSendOtpMutationBody = SendOtpDto;
export type IdentityControllerSendOtpMutationError = void;

/**
 * @summary Send OTP to email address
 */
export const useIdentityControllerSendOtp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityControllerSendOtp>>,
      TError,
      { data: SendOtpDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityControllerSendOtp>>,
  TError,
  { data: SendOtpDto },
  TContext
> => {
  const mutationOptions = getIdentityControllerSendOtpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Verify email OTP and return CipherBox identity JWT
 */
export const identityControllerVerifyOtp = (verifyOtpDto: VerifyOtpDto, signal?: AbortSignal) => {
  return customInstance<IdentityTokenResponseDto>({
    url: `/auth/identity/email/verify-otp`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: verifyOtpDto,
    signal,
  });
};

export const getIdentityControllerVerifyOtpMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof identityControllerVerifyOtp>>,
    TError,
    { data: VerifyOtpDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof identityControllerVerifyOtp>>,
  TError,
  { data: VerifyOtpDto },
  TContext
> => {
  const mutationKey = ['identityControllerVerifyOtp'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof identityControllerVerifyOtp>>,
    { data: VerifyOtpDto }
  > = (props) => {
    const { data } = props ?? {};

    return identityControllerVerifyOtp(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IdentityControllerVerifyOtpMutationResult = NonNullable<
  Awaited<ReturnType<typeof identityControllerVerifyOtp>>
>;
export type IdentityControllerVerifyOtpMutationBody = VerifyOtpDto;
export type IdentityControllerVerifyOtpMutationError = void;

/**
 * @summary Verify email OTP and return CipherBox identity JWT
 */
export const useIdentityControllerVerifyOtp = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof identityControllerVerifyOtp>>,
      TError,
      { data: VerifyOtpDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof identityControllerVerifyOtp>>,
  TError,
  { data: VerifyOtpDto },
  TContext
> => {
  const mutationOptions = getIdentityControllerVerifyOtpMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
