/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import { customInstance } from '../custom-instance';

/**
 * @summary Get API info
 */
export const appControllerGetRoot = (signal?: AbortSignal) => {
  return customInstance<void>({ url: `/`, method: 'GET', signal });
};

export const getAppControllerGetRootQueryKey = () => {
  return [`/`] as const;
};

export const getAppControllerGetRootQueryOptions = <
  TData = Awaited<ReturnType<typeof appControllerGetRoot>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAppControllerGetRootQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetRoot>>> = ({ signal }) =>
    appControllerGetRoot(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof appControllerGetRoot>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AppControllerGetRootQueryResult = NonNullable<
  Awaited<ReturnType<typeof appControllerGetRoot>>
>;
export type AppControllerGetRootQueryError = unknown;

export function useAppControllerGetRoot<
  TData = Awaited<ReturnType<typeof appControllerGetRoot>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetRoot>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetRoot>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerGetRoot<
  TData = Awaited<ReturnType<typeof appControllerGetRoot>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetRoot>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetRoot>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAppControllerGetRoot<
  TData = Awaited<ReturnType<typeof appControllerGetRoot>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get API info
 */

export function useAppControllerGetRoot<
  TData = Awaited<ReturnType<typeof appControllerGetRoot>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof appControllerGetRoot>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAppControllerGetRootQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
