/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * CipherBox API
 * Zero-knowledge encrypted cloud storage API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { InitVaultDto, QuotaResponseDto, VaultResponseDto } from '../models';

import { customInstance } from '../custom-instance';

/**
 * Create a new vault with encrypted keys on first sign-in. Returns 409 Conflict if vault already exists.
 * @summary Initialize user vault
 */
export const vaultControllerInitializeVault = (
  initVaultDto: InitVaultDto,
  signal?: AbortSignal
) => {
  return customInstance<VaultResponseDto>({
    url: `/vault/init`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: initVaultDto,
    signal,
  });
};

export const getVaultControllerInitializeVaultMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vaultControllerInitializeVault>>,
    TError,
    { data: InitVaultDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vaultControllerInitializeVault>>,
  TError,
  { data: InitVaultDto },
  TContext
> => {
  const mutationKey = ['vaultControllerInitializeVault'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vaultControllerInitializeVault>>,
    { data: InitVaultDto }
  > = (props) => {
    const { data } = props ?? {};

    return vaultControllerInitializeVault(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VaultControllerInitializeVaultMutationResult = NonNullable<
  Awaited<ReturnType<typeof vaultControllerInitializeVault>>
>;
export type VaultControllerInitializeVaultMutationBody = InitVaultDto;
export type VaultControllerInitializeVaultMutationError = void;

/**
 * @summary Initialize user vault
 */
export const useVaultControllerInitializeVault = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vaultControllerInitializeVault>>,
      TError,
      { data: InitVaultDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vaultControllerInitializeVault>>,
  TError,
  { data: InitVaultDto },
  TContext
> => {
  const mutationOptions = getVaultControllerInitializeVaultMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieve the vault for the authenticated user.
 * @summary Get user vault
 */
export const vaultControllerGetVault = (signal?: AbortSignal) => {
  return customInstance<VaultResponseDto>({ url: `/vault`, method: 'GET', signal });
};

export const getVaultControllerGetVaultQueryKey = () => {
  return [`/vault`] as const;
};

export const getVaultControllerGetVaultQueryOptions = <
  TData = Awaited<ReturnType<typeof vaultControllerGetVault>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetVault>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVaultControllerGetVaultQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vaultControllerGetVault>>> = ({
    signal,
  }) => vaultControllerGetVault(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vaultControllerGetVault>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VaultControllerGetVaultQueryResult = NonNullable<
  Awaited<ReturnType<typeof vaultControllerGetVault>>
>;
export type VaultControllerGetVaultQueryError = void;

export function useVaultControllerGetVault<
  TData = Awaited<ReturnType<typeof vaultControllerGetVault>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetVault>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vaultControllerGetVault>>,
          TError,
          Awaited<ReturnType<typeof vaultControllerGetVault>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVaultControllerGetVault<
  TData = Awaited<ReturnType<typeof vaultControllerGetVault>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetVault>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vaultControllerGetVault>>,
          TError,
          Awaited<ReturnType<typeof vaultControllerGetVault>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVaultControllerGetVault<
  TData = Awaited<ReturnType<typeof vaultControllerGetVault>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetVault>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get user vault
 */

export function useVaultControllerGetVault<
  TData = Awaited<ReturnType<typeof vaultControllerGetVault>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetVault>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVaultControllerGetVaultQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get current storage usage and limits. Limit is 500 MiB (524,288,000 bytes).
 * @summary Get storage quota
 */
export const vaultControllerGetQuota = (signal?: AbortSignal) => {
  return customInstance<QuotaResponseDto>({ url: `/vault/quota`, method: 'GET', signal });
};

export const getVaultControllerGetQuotaQueryKey = () => {
  return [`/vault/quota`] as const;
};

export const getVaultControllerGetQuotaQueryOptions = <
  TData = Awaited<ReturnType<typeof vaultControllerGetQuota>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetQuota>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVaultControllerGetQuotaQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vaultControllerGetQuota>>> = ({
    signal,
  }) => vaultControllerGetQuota(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vaultControllerGetQuota>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VaultControllerGetQuotaQueryResult = NonNullable<
  Awaited<ReturnType<typeof vaultControllerGetQuota>>
>;
export type VaultControllerGetQuotaQueryError = void;

export function useVaultControllerGetQuota<
  TData = Awaited<ReturnType<typeof vaultControllerGetQuota>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetQuota>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vaultControllerGetQuota>>,
          TError,
          Awaited<ReturnType<typeof vaultControllerGetQuota>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVaultControllerGetQuota<
  TData = Awaited<ReturnType<typeof vaultControllerGetQuota>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetQuota>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vaultControllerGetQuota>>,
          TError,
          Awaited<ReturnType<typeof vaultControllerGetQuota>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVaultControllerGetQuota<
  TData = Awaited<ReturnType<typeof vaultControllerGetQuota>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetQuota>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get storage quota
 */

export function useVaultControllerGetQuota<
  TData = Awaited<ReturnType<typeof vaultControllerGetQuota>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vaultControllerGetQuota>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVaultControllerGetQuotaQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
